name: Merge me!

on:
  pull_request_target:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@d1902dadabfb0cbe5417ec12884f18d780b78825
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.DOTTBOTT_TOKEN }}
          DEPENDS_ON: continuous-integration.yaml
    timeout-minutes: 5
