name: Merge me!

on:
  pull_request_target:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@fix/merge-failed
        with:
          GITHUB_LOGIN: dependabot[bot]
          GITHUB_TOKEN: ${{ secrets.DOTTBOTT_TOKEN }}
          DEPENDS_ON: Continuous Integration
    timeout-minutes: 5
